name: 1.0.$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
  - task: UseDotNet@2
    displayName: 'Installing .Net 2.1.x (Used by SonarCloud)'
    inputs:
      version: '2.1.x'
      packageType: sdk
  - task: UseDotNet@2
    displayName: 'Installing .Net 3.1.x'
    inputs:
      version: '3.1.x'
      packageType: sdk
  - task: SonarCloudPrepare@1
    displayName: 'Preparing SonarCloud Analysis'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'atc-net'
      scannerMode: 'MSBuild'
      projectKey: 'atc-net_atc'
      projectName: 'ATC'
  - task: DotNetCoreCLI@2
    displayName: 'Running dotnet restore'
    inputs:
      command: restore
      projects: 'Atc.sln'
  - task: DotNetCoreCLI@2
    displayName: 'Running dotnet build'
    inputs:
      command: 'build'
      projects: 'Atc.sln'
  - task: DotNetCoreCLI@2
    displayName: 'Running dotnet test'
    inputs:
      command: test
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Creating Nuget Packages'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj;!**/*.Tests.csproj;!**/*.Console.csproj;!**/*.Web.csproj;!**/*.Samples.csproj'
      versioningScheme: 'byBuildNumber'
  - task: SonarCloudAnalyze@1
    displayName: 'Run Code Analysis and Publish Quality Gate Result'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'