name: 1.0.$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: 'Atc.sln'
  - task: DotNetCoreCLI@2
    displayName: 'Create Packages'
    inputs:
      command: pack
      packagesToPack: '**/*.csproj'
      versioningScheme: byBuildNumber
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '**/*.csproj'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'