name: 1.0.$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '3.1.x'
      packageType: sdk
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'atc-net'
      scannerMode: 'MSBuild'
      projectKey: 'atc-net_atc'
      projectName: 'ATC'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: 'Atc.sln'
  - task: VSBuild@1
    displayName: 'Build solution Atc.sln'
    inputs:
      solution: Atc.sln
      platform: 'Any CPU'
      configuration: 'Release'
    timeoutInMinutes: 20
  - task: DotNetCoreCLI@2
    displayName: 'Create Packages'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj;!**/*.Tests.csproj;!**/*.Console.csproj;!**/*.Web.csproj'
      versioningScheme: 'byBuildNumber'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    continueOnError: true
    inputs:
      command: test
      projects: '**/*.csproj'
  - task: SonarCloudAnalyze@1
    displayName: 'Run Code Analysis and Publish Quality Gate Result'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'