name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore packages with dotnet
      run: dotnet restore Atc.sln
    - name: Build with dotnet
      run: dotnet build Atc.sln
    - name: Test with dotnet
      run: dotnet test Atc.sln
